name: Set Ready For Review label
on:
  - status
  - check_run
  - workflow_run
jobs:
  add-label:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Set Ready For Review label
        if: github.event.pull_request.draft == false
        shell: bash
        run: |
          output=$(gh api -H "${accept_header}" -H "${api_header}" repos/${GITHUB_REPOSITORY}/status/${GITHUB_SHA})
          jq_output=$(echo ${output} | jq -c '.statuses[] | {state: .state, context: .context}')
          ready=false
          for row in $(echo "${jq_output}"); do
              _jq() {
              echo ${row} | jq -r ${1}
              }
              if [ $(_jq '.state') == 'failure' ]; then
                  break
              fi
              if [ $(_jq '.state') == 'pending' ] && [ $(_jq '.context') != 'tide' ] ; then
                  break
              fi
              ready=true
          done

          if [ "$ready" == 'true' ]; then
              gh pr edit "$URL" --add-label "Ready For Review"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          accept_header: 'Accept: application/vnd.github+json'
          api_header: 'X-GitHub-Api-Version: 2022-11-28'
          GH_PAGER: ''
          URL: ${{ github.event.pull_request.html_url }}