# Marks all newly opened pull requests as drafts
name: Draft on Open
on:
  pull_request:
    types: [ opened ]

jobs:
  mark-as-draft:
    name: Mark as draft
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Mark as draft
        uses: voiceflow/draft-pr@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  # label_issues:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     issues: write
  #   steps:
  #     - run: gh pr ready "$NUMBER" --undo
  #       env:
  #         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         GH_REPO: ${{ github.repository }}
  #         NUMBER: ${{ github.event.issue.number }}
  #         # LABELS: auto-draft