# Marks all newly opened pull requests as drafts
name: Draft on Open
on:
  pull_request:
    types: [ opened, reopened ]

jobs:
  mark-as-draft:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Set to draft and add comment
        if: github.event.pull_request.draft == false
        shell: bash
        run: >
          gh pr ready "$URL" --undo && 
          printf 'Thanks for the PR! :heart:\nI am marking it as a draft,
          once passing your happy and the PR is passing CI click the
          \"Ready for review\" button below.' |
          gh pr comment "$URL" -F -
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}
